[package]
name = "bts"
version = "1.3.0"
edition = "2018"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }

serde_json = "1.0.78"
serde = { version = "1.0", features = ["derive"] }
glob = "0.3.0"
rand = "0.8.4"
uuid = { version = "0.8", features = ["serde", "v4"] }

tokio-tungstenite = "*"
tokio = { version = "1.17.0", features = ["full"] }
futures-util = "0.3"
futures-channel = "0.3.21"
tungstenite = "0.17.2"
env_logger = "0.9.0"
log = "0.4.14"