[package]
name = "bts"
version = "1.0.0"
edition = "2018"

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
tungstenite = "0.16.0"
serde_json = "1.0.78"
serde = { version = "1.0", features = ["derive"] }